name: Concatenate Files on Merge

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  merge-sources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Clean and create output directory
      run: |
        rm -rf output
        mkdir -p output

    - name: Concatenate files
      run: |
        find Development -type f -name '*.swift' | sort | xargs cat > SubviewsBackport.swift

    - name: Remove SwiftLint commands
      run: |
        sed '/\/\/ swiftlint:/d' SubviewsBackport.swift > temp && mv temp SubviewsBackport.swift

    - name: Prepare LICENSE content
      run: |
        # Prepend "// " to each line in LICENSE and save it to a temp file
        sed 's/^/\/\/ /' LICENSE > license_commented.txt
    
    - name: Add newlines between LICENSE and imports
      run: |
        # Create a file with newline
        echo -e "\n// auto-generated file, do not edit directly\n" > newlines.txt

    - name: Reorder, sort, and remove duplicate imports
      run: |
        # Extract, sort, and remove duplicates from import statements
        awk '/^import / {print}' SubviewsBackport.swift | sort | uniq > sorted_unique_imports.txt

        # Remove import statements from the original file
        awk '!/^import /' SubviewsBackport.swift > code_without_imports.txt

        # Concatenate sorted and unique imports with the rest of the file
        cat sorted_unique_imports.txt code_without_imports.txt > code_with_sorted_imports.txt

    - name: Combine LICENSE, newlines, imports, and remaining content
      run: |
        # Concatenate LICENSE content with two newlines, imports, and the rest of the file
        cat license_commented.txt newlines.txt code_with_sorted_imports.txt > SubviewsBackport.swift
      
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add SubviewsBackport.swift
        git commit -m "Generated SubviewsBackport.swift"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}