name: SwiftFormat

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  swift-format:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    # - name: Install SwiftFormat
      # run: brew install swiftformat
    - name: Run SwiftFormat
      run: swiftformat .
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply SwiftFormat" || echo "No changes to commit"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}